PlayerName = "test2"
PlayerTag = 2
PlayerGold = 5300
PlayerFurthestStage = 0
RedHerbCount = 0
WhiteHerbCount = 0
EmptyBottleCount = 0
ClothCount = 0
RedPotionCount =7
AttackPotionCount = 0
DefencePotionCount = 0
AttackPotionCount = 0
WarriorCount = 1
MageCount = 1
PriestCount = 0
Warrior1 = 1
Mage1 = 1