PlayerName = "test2"
PlayerTag = 2
PlayerGold = 10400
PlayerFurthestStage = 0
RedHerbCount = 0
WhiteHerbCount = 0
EmptyBottleCount = 0
ClothCount = 0
RedPotionCount =8
AttackPotionCount = 0
DefencePotionCount = 0
AttackPotionCount = 0
WarriorCount = 0
MageCount = 0
PriestCount = 0