PlayerName = "TEST"
PlayerTag = 1
PlayerGold = 0
PlayerFurthestStage = 0
RedHerbCount = 560
WhiteHerbCount = 0
EmptyBottleCount = 0
ClothCount = 0
RedPotionCount =167
AttackPotionCount = 0
DefencePotionCount = 0
AttackPotionCount = 0
WarriorCount = 0
MageCount = 0
PriestCount = 0