PlayerName = "test2"
PlayerTag = 2
PlayerGold = 0
PlayerFurthestStage = 0
RedHerbCount = 34
WhiteHerbCount = 0
EmptyBottleCount = 0
ClothCount = 0
RedPotionCount =22
AttackPotionCount = 0
DefencePotionCount = 0
AttackPotionCount = 0
WarriorCount = 1
MageCount = 1
PriestCount = 1
Warrior1 = 20
Mage1 = 20
Priest1 = 20